#----------------------------------------------------------------------------
#
# Platform Game Engine Project by Wohlstand, a free platform for making games of platform genre
# Copyright (c) 2014-2017 Vitaly Novichkov <admin@wohlnet.ru>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#--------------------------------------------------------------------------------
# AppVeyor CI building configuration file for Microsoft Windows Operating system
#                             created 2015-11-25
#--------------------------------------------------------------------------------

version: 0.4.0.3.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

branches:
  only:  # whitelist
    - master

skip_tags: true

skip_commits:
    message: /Created.*\.(png|jpg|jpeg|bmp|gif)/       # Regex for matching commit message

# Operating system (build VM template)
os: unstable

# clone directory
clone_folder: C:\_Repos\PGE-Project
clone_depth:  2  # clone entire repository history if not defined
# Uncommend those two lines to enable RDP (which can be used to debug stuff and test built stuff)
# init:
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  global:
    PLATFORMTOOLSET: "v140"
    GIT_DIR: "C:\\Program Files\\Git\\cmd"
    CMAKE_DIR: "C:\\Program Files\\CMake\\bin"

  matrix:
  # 64 bit build
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: x64
      BIN_DIR: bin-w64
      WINXX_ARCH: win64
      COMPILER: C:\mingw-w64\x86_64-7.1.0-posix-seh-rt_v5-rev0\mingw64\bin
      QT_DIR: C:\Qt\5.9.0-x64\bin
#     COMPILER: C:\MinGW-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin
#     QT_DIR: C:\Qt\5.9.6-x64\bin
    # 32 bit build with Windows XP support
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2013"
      PLATFORM: Win32
      BIN_DIR: bin-w32
      WINXX_ARCH: win32
      COMPILER: C:\Qt\Tools\mingw530_32\bin
      QT_DIR: C:\Qt\5.7\mingw53_32\bin
#     COMPILER: C:\MinGW-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin
#     QT_DIR: C:\Qt\5.6.3-i686\bin # Qt since 5.8 no more supports Windows XP, Keep support for Windows XP yet

install:
  - ps: new-item C:\temp-d -itemtype directory
  - ps: (new-object net.webclient).DownloadFile('http://wohlsoft.ru/docs/Software/Ninja-Build/ninja-win.zip', 'C:\temp-d\ninja-win.zip');
  - ps: if ($env:PLATFORM -eq "x64") { (new-object net.webclient).DownloadFile('http://wohlsoft.ru/docs/Software/QtBuilds/MinGW-w64-x86_64-7.1.0-posix-seh-rt_v5-rev0.7z', 'C:\temp-d\MinGW-w64-x86_64-7.1.0-posix-seh-rt_v5-rev0.7z'); }
  - ps: if ($env:PLATFORM -eq "x64") { (new-object net.webclient).DownloadFile('http://wohlsoft.ru/docs/Software/QtBuilds/Qt-5.9.0-x64-shared-mingw-w64-posix-seh-7-1-0.7z', 'C:\temp-d\Qt-5.9.0-x64-shared-mingw-w64-posix-seh-7-1-0.7z'); }
  - ps: |
      if ($env:PLATFORM -eq "x64") {
      Set-Alias sevenzip "C:\Program Files\7-Zip\7z.exe"
      sevenzip x C:\temp-d\MinGW-w64-x86_64-7.1.0-posix-seh-rt_v5-rev0.7z -oC:\MinGW-w64;
      sevenzip x C:\temp-d\Qt-5.9.0-x64-shared-mingw-w64-posix-seh-7-1-0.7z -oC:\Qt; }
#  - ps: if ($env:PLATFORM -eq "x64") { (new-object net.webclient).DownloadFile('http://wohlsoft.ru/docs/Software/MinGW/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z', 'C:\temp-d\x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z'); }
#  - ps: if ($env:PLATFORM -eq "Win32") { (new-object net.webclient).DownloadFile('http://wohlsoft.ru/docs/Software/MinGW/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z', 'C:\temp-d\i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z'); }
#  - ps: if ($env:PLATFORM -eq "x64") { (new-object net.webclient).DownloadFile('http://wohlsoft.ru/docs/Software/QtBuilds/Qt-5.9.6-x64-mingw-w64-8.1.0-shared-release.7z', 'C:\temp-d\Qt-5.9.6-x64-mingw-w64-8.1.0-shared-release.7z'); }
#  - ps: if ($env:PLATFORM -eq "Win32") { (new-object net.webclient).DownloadFile('http://wohlsoft.ru/docs/Software/QtBuilds/Qt-5.6.3-i686-mingw-w64-8.1.0-shared-release.7z', 'C:\temp-d\Qt-5.6.3-i686-mingw-w64-8.1.0-shared-release.7z'); }
#  - ps: |
#      if ($env:PLATFORM -eq "x64") {
#      Set-Alias sevenzip "C:\Program Files\7-Zip\7z.exe"
#      sevenzip x C:\temp-d\x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z -oC:\MinGW-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0;
#      sevenzip x C:\temp-d\Qt-5.9.6-x64-mingw-w64-8.1.0-shared-release.7z -oC:\Qt; }
#  - ps: |
#      if ($env:PLATFORM -eq "Win32") {
#      Set-Alias sevenzip "C:\Program Files\7-Zip\7z.exe"
#      sevenzip x C:\temp-d\i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z -oC:\MinGW-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0;
#      sevenzip x C:\temp-d\Qt-5.6.3-i686-mingw-w64-8.1.0-shared-release.7z -oC:\Qt; }
  - cmd: "\"C:\\Program Files\\7-Zip\\7z.exe\" x C:\\temp-d\\ninja-win.zip -o%COMPILER%"
  - cmd: git submodule init
  - cmd: git submodule update
  - cmd: echo set QtDir=%QT_DIR%>> _paths.bat
  - cmd: echo set MinGW=%COMPILER%>> _paths.bat
  - cmd: if [%PLATFORM%]==[x64] echo set MINGWx64Dest=yes>> _paths.bat
#  - cmd: if [%PLATFORM%]==[Win32] echo set MINGWx32Dest=yes>> _paths.bat
  - cmd: echo set GitDir=%GIT_DIR%>> _paths.bat
  - cmd: echo set CMakeDir=%CMAKE_DIR%>> _paths.bat
  - cmd: echo date +'%%%%Y-%%%%m-%%%%d %%%%H:%%%%M:%%%%S' > temp.sh
  - cmd: type temp.sh
  - cmd: "\"C:\\Program Files\\Git\\bin\\bash.exe\" temp.sh > build_date_dev_%WINXX_ARCH%.txt"
  - cmd: type build_date_dev_%WINXX_ARCH%.txt
  - cmd: del temp.sh

build_script:
#  - cmd: build_deps.bat buildlibs nopause
#  - cmd: build.bat nopause # noengine nocalibrator nogifs2png nopng2gifs nolazyfixtool nomanager nomaintainer nomusicplayer
#  - cmd: cd _Misc\dev_scripts\deploy\
#  - cmd: if [%PLATFORM%]==[Win32] deploy_windows_dynamic.bat nopause
#  - cmd: if [%PLATFORM%]==[Win32] deploy_windows_dynamic_32_w64.bat nopause
#  - cmd: if [%PLATFORM%]==[x64] deploy_windows_dynamic_x64.bat nopause
#  - cmd: cd ..\..\..\
  - cmd: build.bat nopause cmake-it ninja deploy
  - md %BIN_DIR%
  - md %BIN_DIR%\_packed
  - move bin-cmake-release\_packed\*.zip %BIN_DIR%\_packed

artifacts:
  - path: '$(BIN_DIR)\_packed\pge-project-dev-$(WINXX_ARCH).zip'
  - path: '$(BIN_DIR)\_packed\install-pge-common-dev-$(WINXX_ARCH).zip'
  - path: '$(BIN_DIR)\_packed\install-pge-editor-dev-$(WINXX_ARCH).zip'
  - path: '$(BIN_DIR)\_packed\install-pge-engine-dev-$(WINXX_ARCH).zip'
  - path: '$(BIN_DIR)\_packed\install-pge-tools-dev-$(WINXX_ARCH).zip'
  - path: '$(BIN_DIR)\_packed\pge-maintainer-dev-$(WINXX_ARCH).zip'     #Standalone package of PGE Maintainer (work outside PGE)
  - path: '$(BIN_DIR)\_packed\pge-musplay-dev-$(WINXX_ARCH).zip'        #Standalone package of PGE MusPlay (work outside PGE)
  - path: 'build_date_dev_$(WINXX_ARCH).txt'

deploy:
  - provider: Environment
    name: WohlnetFTP
