#----------------------------------------------------------------------------
#
# Platform Game Engine Project by Wohlstand, a free platform for making games of platform genre
# Copyright (c) 2014-2015 Vitaly Novichkov <admin@wohlnet.ru>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#--------------------------------------------------------------------------------
# AppVeyor CI building configuration file for Microsoft Windows Operating system
#                             created 2015-11-25
#--------------------------------------------------------------------------------

# version format
version: 0.3.3.3.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

branches:
  # whitelist
  only:
    - master

skip_tags: true

skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/       # Regex for matching commit message

# Operating system (build VM template)
os: unstable

# clone directory
clone_folder: C:\_Repos\PGE-Project

clone_depth: 1                      # clone entire repository history if not defined

# Uncommend those two lines to enable RDP (which can be used to debug stuff and test built stuff)
# init:
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  # - echo This is batch
  # batch commands start from cmd:
  # - cmd: echo This is batch again
  # - cmd: set MY_VAR=12345
  - echo set QtDir=C:\Qt\5.5\mingw492_32\bin>> _paths.bat
  - echo set MinGW=C:\Qt\Tools\mingw492_32\bin>> _paths.bat
  - echo set GitDir=C:\Program Files\Git\cmd>> _paths.bat
  
build_script:
  - build_deps.bat nopause
  - build.bat nopause noengine nocalibrator nogifs2png nopng2gifs nolazyfixtool nomanager nomaintainer
  - cd _Misc\dev_scripts\deploy\
  - deploy_windows_dynamic.bat nopause
  - cd ..\..\..\
  
artifacts:
- path: bin-w32\_packed\pge-project-dev-win32.zip
- path: bin-w32\_packed\install-pge-common-dev-win32.zip
- path: bin-w32\_packed\install-pge-editor-dev-win32.zip
#- path: bin-w32\_packed\install-pge-engine-dev-win32.zip #This archive has no built applications (engine disabled to don't excite building timeout)
#- path: bin-w32\_packed\install-pge-tools-dev-win32.zip #This archive has no built applications (toosl are disabled to don't excite building timeout)

deploy:
- provider: Environment
  name: WohlnetFTP

